### ISSUE TITLE
[Repos Tareas] Todavía no tengo Repo

### ISSUE THREAD

**Issue by HenryBlairG** [PUC-IIC2283/2020-IIC2283#2]
Hola,

Ya rellené el form con mi usuario de GitHub, pero no me ha llegado ninguna invitación a colaborar ni nada por el estilo. He estado un poco desconcentrado del proceso y ahora que se publicó la tarea me bajó la duda de si todavía no se crean los repos o soy yo que respondí mal o tarde :crying_cat_face: Desde ya les agradezco mucho toda la ayuda que me puedan dar :raised_hands:

**Comment by mmunos** [comment]
Según veo tienes un pending invite. Tu repo es https://github.com/PUC-IIC2283/2020-henryblairg.

Para los demás que tengan la misma duda su repo está en https://github.com/PUC-IIC2283/2020-tuusuariodegit.

**Comment by pnheinsohn** [comment]
Hola! a mi me sale que la invitación al repo expiró D:

**Comment by mmunos** [comment]
Sorry por la demora. Vela ahora.

**Comment by aeperalta** [comment]
Hola! También me aparece que la invitación expiró :( @mmunos

**Comment by mmunos** [comment]
@aeperalta ve si te llegó

**Comment by aeperalta** [comment]
ahí me llegó, muchas gracias!
