### ISSUE TITLE
[T1-P1] complejidad esperada

### ISSUE THREAD

**Issue by aaguilarg** [PUC-IIC2283/2020-IIC2283#3]
Hola,
En la pregunta 1 se indica que la complejidad esperada es O(n), sin embargo mas abajo en el hint, se indica:
>Piense cómo bajar esta complejidad a O(n^2) y luego cómo usar una tabla de tamaño c×n para calcular el valor pedido en tiempo O(n) con programación dinámica, donde c es una constante pequeña.

Lo que desprendo que se lograría encontrar un algoritmo con complejidad O(n^2).
Entonces mi pregunta es si es que la complejidad esperada de O(n) es la correcta y yo entendí mal el hint o podemos encontrar un algoritmo con complejidad O(n^2)?

**Comment by mmunos** [comment]
Yo pensé el hint como 3 pasos: primero les mostré la solución ingenua. Después que se pueden ahorrar un factor lineal y que se puede hacer en O(n^2). Después de eso propuse que piensen en una solución en O(n) que utiliza la tabla de tamaño c x n. Esta es la solución esperada.

De todas maneras, si tienen una solución en tiempo lineal que no necesita la tabla va a ser aceptada también.

**Comment by aaguilarg** [comment]
Perfecto, muchas gracias! :smile:
